config/routes.rb
Spree::Core::Engine.routes.draw do

  # Add your extension routes here
  namespace :admin do
    resources :themes, only: [:index, :destroy] do

      member do
        patch :state_change
        patch :download
      end

      collection do
        post :upload
      end

      resources :templates, controller: :themes_templates, only: [:index, :new, :create, :edit, :update]

      resource :preview, controller: :themes_preview, only: [:show, :destroy]
    end

  end
end

app/models/spree/themes_template.rb
module Spree
  class ThemesTemplate < Spree::Base

    DEFAULT_LOCALE = 'en'
    DEFAULT_PATH = File.join('public', 'vinsol_spree_themes')
    ASSETS_FILE_EXTENSIONS = ['.js', '.css']

    # this attr attribute is used when templates are created from admin end.
    attr_accessor :created_by_admin

    ## VALIDATIONS ##
    validates :path, presence: true
    validates :format, inclusion: Mime::SET.symbols.map(&:to_s),
                       allow_nil: true
    validates :locale, inclusion: I18n.available_locales.map(&:to_s)
    validates :handler, inclusion: ActionView::Template::Handlers.extensions.map(&:to_s),
                        allow_nil: true

    ## ASSOCIATIONS ##
    belongs_to :theme

    ## CALLBACKS ##
    before_validation :set_default_locale, unless: :locale?
    before_create :set_public_path, if: :created_by_admin
    after_save :update_cache_timestamp
    after_save :update_public_file
    after_save :precompile_assets, if: [:theme_published?, :assets_file?]

    ## DELEGATES ##
    delegate :name, to: :theme, prefix: true

    self.whitelisted_ransackable_attributes = %w( name path format handler )

    private

      def update_cache_timestamp
        Rails.cache.write(Spree::ThemesTemplate::CacheResolver.cache_key, Time.current)
      end

      def set_default_locale
        self.locale = DEFAULT_LOCALE
      end

      def set_public_path
        self.path = File.join(DEFAULT_PATH, theme_name, path)
      end

      def update_public_file
        FileGeneratorService.create(self)
      end

      def precompile_assets
        assets_compiler = AssetsPrecompilerService.new(theme)
        assets_compiler.minify
        assets_compiler.copy_assets
      end

      def theme_published?
        theme.published?
      end

      def assets_file?
        ASSETS_FILE_EXTENSIONS.include? File.extname(name)
      end

  end
end

app/models/spree/themes_template/cache_resolver.rb
module Spree
  class ThemesTemplate::CacheResolver < ActionView::FileSystemResolver

    FRAGMENT_CACHE_PATH_REGEX = /\A(views\/spree_cache)/
    FRAGMENT_CACHE_KEY = 'spree_cache'

    def initialize(path)
      super(path)
    end

    def find_all(*args)
      clear_cache_if_necessary
      super
    end

    def self.cache_key
      ActiveSupport::Cache.expand_cache_key('updated_at', 'loaded_templates')
    end

    private

      def clear_cache_if_necessary
        last_updated = Rails.cache.fetch(Spree::ThemesTemplate::CacheResolver.cache_key) { Time.current }

        if @cache_last_updated.nil? || @cache_last_updated < last_updated
          Rails.logger.info 'Expiring cache and reloading new template content....'
          # expiring fragment caching used in spree views 
          ActionController::Base.new().expire_fragment(FRAGMENT_CACHE_PATH_REGEX)
          # clearing template caching.
          clear_cache

          @cache_last_updated = last_updated
        end
      end

  end
end

app/controllers/spree/admin/themes_templates_controller.rb
module Spree
  module Admin
    class ThemesTemplatesController < Spree::Admin::BaseController

      before_action :load_theme, only: [:index, :new, :create, :edit, :update]
      before_action :load_template, only: [:edit, :update]

      def index
      end

      def new
        @template = @theme.themes_templates.build
      end

      def create
        @template = @theme.themes_templates.build(new_template_params)
        @template.created_by_admin = true

        if @template.save
          redirect_to admin_theme_templates_path(@theme)
        else
          render :new
        end
      end

      def edit
      end

      def update
        @template.update(template_params)
        render :edit
      end

      private

        def load_theme
          @theme = Spree::Theme.find_by(id: params[:theme_id])
          unless @theme
            redirect_to admin_themes_path
          end
        end

        def load_template
          @template = @theme.templates.find_by(id: params[:id])
          unless @template
            redirect_to admin_theme_templates_path(@theme)
          end
        end

        def template_params
          params.require(:themes_template).permit(:body)
        end

        def new_template_params
          params.require(:themes_template).permit(:body, :name, :path)
        end

    end
  end
end

app/views/spree/admin/themes_templates/_editor.html.erb
<% form_path = @template.nil? ? '#' : admin_theme_template_path(@theme, @template) %>

<% if @template %>
  <div data-hook="admin_theme_form_header">
    <%= render partial: 'spree/admin/shared/error_messages', locals: { target: @template } %>
  </div>
<% end %>

<%= form_for @template || Spree::ThemesTemplate.new, url: form_path, method: :put, html: { multipart: true }, remote: true do |f| %>
  <fieldset>
    <div data-hook="admin_template_form_fields" class="admin-editor-section">
      <div data-hook="admin_template_form">
          <div data-hook="admin_template_form_body">
            <%= f.label :body, Spree.t(:body) %>
            <%= f.text_area :body, class: 'form-control body', rows: '20' %>
          </div>
      </div>
    </div>

    <div class="form-actions" data-hook="buttons">
      <%= button Spree.t('actions.update'), 'refresh', 'submit', { class: 'btn-success', data: { disable_with: "#{ Spree.t(:saving) }..." }} %>
      <span class="or"><%= Spree.t(:or) %></span>
      <%= button_link_to Spree.t('actions.cancel'), admin_themes_path, icon: 'delete' %>
    </div>
  </fieldset>
<% end %>

<!-- script to initialize code mirror editor on textarea -->
<%= javascript_include_tag 'spree/backend/main.js' %>

app/views/spree/admin/themes_templates/_template.html.erb
<tr id="<%= spree_dom_id template %>" data-hook="admin_templates_index_rows">
  <td class='template_name'><%= link_to template.name, edit_admin_theme_template_path(@theme, template), class: 'template-name' %></td>
  <td class='template_path'><%= template.path %></td>
  <td class='template_format'><%= template.format %></td>
  <td class='template_handler'><%= template.handler %></td>

  <td data-hook="admin_template_index_row_actions" class="actions actions-2 text-right">
    <%= link_to edit_admin_theme_template_path(@theme, template), class: 'btn btn-primary btn-sm  with-tip action-edit no-text', title: '', 'data-original-title' => 'Edit' do %>
      <span class="icon icon-edit"></span>
    <% end %>
  </td>
</tr>

app/views/spree/admin/themes_templates/edit.html.erb
<% content_for :page_title do %>
  <%= link_to Spree.t(:templates), admin_theme_templates_path(@theme) %> /
  <%= File.join(@template.path, @template.name) %>
<% end %>

<% content_for :head do %>
  <%= javascript_include_tag 'spree/backend/editor' %>
  <%= stylesheet_link_tag 'spree/backend/editor' %>
<% end %>

<div data-hook='template-editor'>
  <%= render partial: 'editor' %>
</div>

app/views/spree/admin/themes_templates/edit.js.erb
$("[data-hook='template-editor']").html("<%= escape_javascript render(partial: 'editor') %>")

app/views/spree/admin/themes_templates/index.html.erb
<% content_for :head do %>
  <%= javascript_include_tag 'spree/backend/jquery.treemenu' %>
  <%= stylesheet_link_tag 'spree/backend/jquery.treemenu' %>
  <%= javascript_include_tag 'spree/backend/editor' %>
  <%= stylesheet_link_tag 'spree/backend/editor' %>
<% end %>

<% content_for :page_title do %>
  <%= link_to Spree.t(:templates), admin_themes_path %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:new_template), new_admin_theme_template_url, class: "btn-success", icon: 'add', id: 'admin_new_theme_template_link' %>
<% end %>

<div class="row">
  <div class="col-md-push-9 col-md-3" id="tree-menu-sidebar">
    <% filepath = File.join(Rails.root, 'public', 'vinsol_spree_themes', @theme.name) %>
    <%= display_filetree_structure(@theme, filepath).html_safe %>
  </div>

  <div data-hook='template-editor' class="col-md-pull-3 col-md-9">
    <%= render partial: 'editor' %>
  </div>
</div>

<%= javascript_include_tag 'spree/backend/template' %>

app/views/spree/admin/themes_templates/new.html.erb
<% content_for :page_title do %>
  <%= link_to Spree.t(:templates), admin_theme_templates_path(@theme) %> /
  <%= Spree.t(:new_template) %>
<% end %>

<% content_for :head do %>
  <%= javascript_include_tag 'spree/backend/editor' %>
  <%= stylesheet_link_tag 'spree/backend/editor' %>
<% end %>

<div data-hook="admin_theme_form_header">
  <%= render partial: 'spree/admin/shared/error_messages', locals: { target: @theme } %>
</div>

<%= form_for @template, url: admin_theme_templates_path(@theme, @template), method: :post, html: { multipart: true } do |f| %>
  <fieldset>

    <div class="row">
      <div class="col-md-8">
        <div data-hook="admin_template_form_name">
          <%= f.label :name, Spree.t(:name) %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-md-8">
        <div data-hook="admin_template_form_path">
          <%= f.label :path, Spree.t(:path) %>
          <%= f.text_field :path, class: 'form-control' %>
          <small><%= "(path will be appended to <b>public/themes/#{ @theme.name }/</b>)".html_safe %></small>
        </div>
      </div>
    </div>

    <div data-hook="admin_template_form_fields">
      <div class="row">
        <div class="col-md-8">
          <div data-hook="admin_template_form_body">
            <%= f.label :body, Spree.t(:body) %>
            <%= f.text_area :body, class: 'form-control body', rows: '20' %>
          </div>
        </div>
      </div>
    </div>

    <div class="form-actions" data-hook="buttons">
      <%= button Spree.t('actions.update'), 'refresh', 'submit', { class: 'btn-success', data: { disable_with: "#{ Spree.t(:saving) }..." }} %>
      <span class="or"><%= Spree.t(:or) %></span>
      <%= button_link_to Spree.t('actions.cancel'), admin_theme_templates_path(@theme), icon: 'delete' %>
    </div>
  </fieldset>
<% end %>

<%= javascript_include_tag 'spree/backend/main.js' %>