config/routes.rb
Spree::Core::Engine.routes.draw do

  # Add your extension routes here
  namespace :admin do
    resources :themes, only: [:index, :destroy] do

      member do
        patch :state_change
        patch :download
      end

      collection do
        post :upload
      end

      resources :templates, controller: :themes_templates, only: [:index, :new, :create, :edit, :update]

      resource :preview, controller: :themes_preview, only: [:show, :destroy]
    end

  end
end

app/models/spree/theme.rb
module Spree
  class Theme < Spree::Base

    DEFAULT_NAME = %w(default)
    DEFAULT_STATE = 'drafted'
    TEMPLATE_FILE_CONTENT_TYPE = 'application/zip'
    STATES = %w(drafted compiled published)
    THEMES_PATH = File.join(Rails.root, 'public', 'vinsol_spree_themes')
    CURRENT_THEME_PATH = File.join(THEMES_PATH, 'current')
    ASSET_CACHE_PATH = File.join(Rails.root, 'tmp', 'cache')

    has_attached_file :template_file, storage: :filesystem,
                                      path: 'public/system/spree/themes/:filename'

    ## VALIDATIONS ##
    validates_attachment :template_file, presence: true,
                                         content_type: { content_type: TEMPLATE_FILE_CONTENT_TYPE }
    do_not_validate_attachment_file_type :template_file

    validates :name, presence: true,
                     uniqueness: { case_sensitive: false }
    validates :state, inclusion: { in: STATES }

    # FIX_ME_PG:- check for atleast one published theme.
    # validate :ensure_atleast_one_published_theme, if: :state_changed?, unless: :published?

    ## ASSOCIATIONS ##
    has_many :themes_templates, dependent: :destroy

    ## CALLBACKS ##
    before_validation :set_name, if: :template_file?
    before_validation :set_state, unless: :state?
    after_commit :extract_template_zip_file, on: :create
    # before_destroy :ensure_not_published, prepend: true
    after_destroy :delete_from_file_system

    # FIX_ME_PG:- Need to have default state to compiled when uploading theme. Set state after zip file extraction.
    # after_create :set_state_to_compile

    ## SCOPES ##
    scope :published, -> { where(state: 'published') }
    scope :default, -> { where(name: DEFAULT_NAME) }

    alias_method :templates, :themes_templates

    self.whitelisted_ransackable_attributes = %w( name state )

    ## STATE MACHINES ##
    state_machine initial: :drafted do
      before_transition drafted: :compiled do |theme, transition|
        begin
          theme.assets_precompile
          theme.update_cache_timestamp
        rescue Exception => e
          theme.errors.add(:base, e)
        end
      end

      before_transition compiled: :published do |theme, transition|
        begin
          theme.remove_current_theme
          theme.apply_new_theme
          theme.remove_cache
          theme.update_cache_timestamp
        rescue Exception => e
          theme.errors.add(:base, e)
        end
      end

      event :draft do
        transition from: [:published, :compiled], to: :drafted
      end

      event :compile do
        transition from: :drafted, to: :compiled
      end

      event :publish do
        transition from: [:compiled, :drafted], to: :published
      end
    end

    def assets_precompile
      AssetsPrecompilerService.new(self).minify
    end

    def remove_current_theme
      Spree::Theme.published.each(&:draft)
      File.delete(CURRENT_THEME_PATH) if File.exist?(CURRENT_THEME_PATH)
    end

    def apply_new_theme
      source_path = File.join(THEMES_PATH, name)
      FileUtils.ln_sf(source_path, CURRENT_THEME_PATH)
      AssetsPrecompilerService.new(self).copy_assets
    end

    def open_preview
      precompile_assets = AssetsPrecompilerService.new(self)
      precompile_assets.minify
      precompile_assets.copy_preview_assets
      remove_cache
      # update_cache_timestamp
    end

    def close_preview
      remove_cache
      # update_cache_timestamp
    end

    def update_cache_timestamp
      Rails.cache.write(Spree::ThemesTemplate::CacheResolver.cache_key, Time.current)
    end

    def remove_cache
      FileUtils.remove_dir(ASSET_CACHE_PATH) if File.exists?(ASSET_CACHE_PATH)
    end

    private

      # def ensure_atleast_one_published_theme
      #   errors.add(:base, Spree.t('models.theme.minimum_active_error')) unless Spree::Theme.published.one?
      # end

      def set_name
        self.name = File.basename(template_file_file_name, File.extname(template_file_file_name))
      end

      def set_state
        self.state = DEFAULT_STATE
      end

      def extract_template_zip_file
        ZipFileExtractor.new(template_file.path, self).extract
      end

      def delete_from_file_system
        source_dir = File.join(THEMES_PATH, name)

        # This makes sure that the directory exists when deleting the theme.
        Dir.mkdir(source_dir) unless Dir.exists?(source_dir)
        FileUtils.remove_dir(source_dir)
      end

      def ensure_not_published
        if published?
          errors.add(:base, Spree.t('models.theme.no_destory_error'))
          throw(:abort)
        end
      end

      # def set_state_to_compile
      #   self.compile!
      # end

  end
end

app/controllers/spree/admin/themes_controller.rb
module Spree
  module Admin
    class ThemesController < Spree::Admin::BaseController
      skip_before_action :authorize_admin
      skip_before_action :verify_authenticity_token, only: [:state_change]
      before_action :load_theme, only: [:state_change, :destroy, :download]
      before_action :load_themes

      def index
        @theme = Spree::Theme.new
      end

      def upload
        @theme = Spree::Theme.new(theme_params)
        if @theme.save
          flash[:notice] = Spree.t('flash.admin.themes.upload.success', name: @theme.name)
          redirect_to admin_themes_path
        else
          flash[:error] = Spree.t('flash.admin.themes.upload.failure', name: @theme.name)
          render :index
        end
      end

      def state_change
        state = case params[:state]
                when 'compiled' then @theme.compile
                when 'published' then @theme.publish
                else false
                end
        if state
          flash[:notice] = Spree.t('flash.admin.themes.state_change.success', state: params[:state], name: @theme.name)
          redirect_to admin_themes_path
        else
          flash[:error] = Spree.t('flash.admin.themes.state_change.failure', state: params[:state], name: @theme.name, errors: @theme.errors.full_messages.join(', '))
          render :index
        end
      end

      def download
        begin
          zipfile = ZipFileBuilder.new(@theme)
          zipfile.archive
          send_file(zipfile.output_path, disposition: 'attachment', filename: zipfile.name)
        rescue Exception => e
          flash[:error] = Spree.t('flash.admin.themes.download.failure', name: @theme.name, errors: e.message)
          render :index
        end
      end

      def destroy
        if @theme.destroy
          flash[:notice] = Spree.t('flash.admin.themes.destroy.success', name: @theme.name)
          redirect_to admin_themes_path
        else
          flash[:error] = Spree.t('flash.admin.themes.destroy.failure', name: @theme.name, errors: @theme.errors.full_messages.join(', '))
          render :index
        end
      end

      private

        def theme_params
          return {} unless params[:theme]
          params.require(:theme).permit(:template_file)
        end

        def load_themes
          @search = Spree::Theme.search(params[:q])
          @themes = @search.result.order(:name).page(params[:page]).per(params[:per_page])
        end

        def load_theme
          @theme = Spree::Theme.find_by(id: params[:id])
          unless @theme
            redirect_to admin_themes_path
          end
        end

    end
  end
end

app/views/spree/admin/themes/_themes.html.erb
<!-- LISTING ALL THE THEMES -->
<div class="themes-container">

  <% sorted_themes(@themes).each do |theme| %>
    <div class="theme theme-col col-md-4 col-sm-6 <%= theme.state %>">
      <div class="theme-block">
        <div class="thumbnail cmn-height-block">
          <%= link_to image_tag(snapshot_path(theme)), admin_theme_templates_path(theme), class: 'img-responsive theme-image' %>
        </div>

        <div class="theme-content">
          <div class="theme-name-area">
            <h2 class="theme-name"><%= theme.name %></h2>
            
              <div class="btn-group dropup">
                <button type="button" class="btn btn-danger dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="glyphicon glyphicon-option-horizontal more-action-glyphicon"></i></button>

              <div class="dropdown-menu">
                <% if theme.drafted? %>
                  <%= link_to Spree.t('actions.compiled'), state_change_admin_theme_path(theme, state: 'compiled'), method: :patch, class: 'dropdown-item' %>
                <% elsif theme.compiled? %>
                  <%= link_to Spree.t('actions.published'), state_change_admin_theme_path(theme, state: 'published'), method: :patch, class: 'dropdown-item' %>
                <% end %>
                
                <% unless theme.published? %>
                  <%= link_to 'Delete', admin_theme_path(theme), method: :delete, class: 'dropdown-item', data: { confirm: 'Are you sure?' } %>
                <% end %>

                <%= link_to Spree.t('actions.download'), download_admin_theme_path(theme), method: :patch, class: 'dropdown-item action-download' %>
              </div>
            </div>
          </div>
        </div>

        <div class="theme-action-view">
          <%= link_to Spree.t(:templates), admin_theme_templates_path(theme) , class: 'btn btn-primary btn-sm' %>
          <%= link_to Spree.t('actions.preview'), admin_theme_preview_path(theme_id: theme), class: 'btn btn-info btn-sm', target: '_blank' %>
        </div>
      </div>
   </div>
  <% end %>
</div>

<%= paginate @themes %>

app/views/spree/admin/themes/_upload.html.erb
<%= form_for @theme, url: upload_admin_themes_path, method: :post do |f| %>
  <div class="updload-theme-panel col-md-4 col-sm-6" data-hook="theme-file-upload-form">
    <div class="upload-theme-col">
      <label class="cmn-height-block text-center">
        <%= f.file_field :template_file, class: 'form-control' %>
        <div class="file-btn-helper">
          <i class="glyphicon glyphicon-upload upload-icon"></i><br />
          ADD NEW THEME
        </div>
      </label>
    </div>
  </div>

  <div class="form-actions hidden" data-hook="buttons">
    <%= f.submit Spree.t('actions.upload'), class: 'btn-success' %>
  </div>
<% end %>

app/views/spree/admin/themes/index.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:themes) %>
  <span class="badge"><%= @themes.size %></span>
<% end %>


<!-- this error partial should only be called when uploading the theme. -->
<% unless @theme.persisted? %>
  <div data-hook="admin_theme_upload_form_header">
    <%= render partial: 'spree/admin/shared/error_messages', locals: { target: @theme } %>
  </div>
<% end %>

<% content_for :table_filter_title do %>
  <%= Spree.t(:search) %>
<% end %>

<% content_for :table_filter do %>
  <div data-hook="admin_theme_index_search">
    <%= search_form_for [:admin, @search], url: admin_themes_path do |f| %>
      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <%= f.label Spree.t(:name) %>
            <%= f.text_field :name_cont, class: "form-control js-quick-search-target" %>
          </div>
        </div>

        <div class="col-md-6">
          <div class="form-group">
            <%= label_tag Spree.t(:state) %>
            <%= f.select :state_eq, Spree::Theme.state_machines[:state].states.map { |state| [Spree.t("theme_states.#{ state.name }"), state.value] }, { include_blank: true }, class: 'select2 js-filterable' %>
          </div>
        </div>
      </div>

      <div data-hook="admin_users_index_search_buttons" class="form-actions">
        <%= button Spree.t(:search), 'search' %>
      </div>
    <% end %>
  </div>
<% end %>

<div class="theme-row row">
  <%= render partial: 'upload' %>
  <div class="file-visible-xs visible-xs"></div>
  <%= render partial: 'themes' %>
</div>

<%= javascript_include_tag 'spree/backend/theme.js' %>